AllCops:
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Exclude:
    - 'Rakefile'
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Exclude:
    - 'Rakefile'
Style/Documentation:
  Enabled: false
Rails/HttpPositionalArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FileName:
  Exclude:
    - 'spec/open_spf/**/*'
