sudo: false
language: ruby
rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-9.1.5.0
addons:
  code_climate:
    repo_token: 437199ed4348853fa1dd6561b2e17a5668a7a6e78485d7ac3a21d12670fb6f2f
after_success:
  - bundle exec codeclimate-test-reporter
